[user]
#经纪公司代码
BrokerID = 0018
#用户代码
UserID = 10016991
#密码
Password = 135246
#密码
SetPasswd = 878787
#用户端产品信息
UserProductInfo = 
#认证码
AuthCode = VL2LA8T11NQ9WR13
#App代码
AppID = mk_mk_0.0.1
#接口端产品信息
InterfaceProductInfo =
#协议信息
ProtocolInfo = 
#Mac地址
MacAddress = 
#动态密码
OneTimePassword = 
#终端IP地址
ClientIPAddress = 183.230.72.28
#登录备注
LoginRemark = 
#终端IP端口
ClientIPPort =41205

[td]
#前置机网络地址
FrontAddr = tcp://183.230.72.28:41205

[md]